config/routes.rb
Scaffold::Application.routes.draw do
  devise_for :users, skip: [:registrations], controllers: {sessions: 'common/sessions'}

  root 'admin/users#index'
  get 'admin' => 'admin/users#index'
  namespace :front do |front|
    namespace :users do
      get :show
      post :sign_up
      post :validate, action: :validate!
      get :current
      post :sign_in_for_web
      post :sign_out_for_web
      get :get_rank
      post :user_approve
      get :search_friend
      get :school_email_approve
      get :get_total_rank
      get :get_total_rank_for_angular
      post :update
      post :update_only_four_info
    end
    resources :contacts do
      collection do
        get :upload
        post :upload_file
        get :tree_data, format: 'json'
      end
    end

    get 'users/edit' => 'users#edit'
    patch 'users/:id' => 'users#update'
    get 'users/update_password' => 'users#update_password'
    patch 'users/update_password' => 'users#update_password'
    resources :user_bills, only: [:index, :show]
    resources :answers do
      collection do
        post 'praise'
        get 'index_for_angular'
        get 'user_already_answer'
        get 'user_already_answer_for_angular'
        get 'answers_praise_num'
        post 'create_with_picture'
      end
    end
    resources :articles
    resources :article_types
    post 'association/judge_praise' => 'association#judge_praise'
    post 'association/fellow_list' => 'association#fellow_list'
    get 'association/fellow_list' => 'association#fellow_list'
    resources :fellows
    resources :majors
    resources :notices
    resources :questions do
      collection do
        get 'index_for_angular'
        post 'search'
        get 'recommend_info'
        get 'user_already_ask'
        get 'add_read_num'
        get 'question_hottest'
        get 'recommend_info_for_angular'
        get 'user_already_ask_for_angular'
        get 'question_hottest_for_angular'
        post 'create_with_picture'
      end
    end
    resources :societies
    resources :sources
    resources :sub_colleges
  end

  namespace :admin do |admin|

    get 'roles/tree_data/:type' => 'roles#tree_data'
    post 'roles/destroy_multi' => 'roles#destroy_multi'
    post 'users/destroy_multi' => 'users#destroy_multi'
    post 'permissions/destroy_multi' => 'permissions#destroy_multi'
    post 'organizations/destroy_multi' => 'organizations#destroy_multi'
    post 'code_tables/destroy_multi' => 'code_tables#destroy_multi'
    post 'attachments/destroy_multi' => 'attachments#destroy_multi'
    post 'answers/destroy_multi' => 'answers#destroy_multi'
    post 'article_types/destroy_multi' => 'article_types#destroy_multi'
    post 'articles/destroy_multi' => 'articles#destroy_multi'
    post 'associations/destroy_multi' => 'associations#destroy_multi'
    post 'fellows/destroy_multi' => 'fellows#destroy_multi'
    post 'majors/destroy_multi' => 'majors#destroy_multi'
    post 'notices/destroy_multi' => 'notices#destroy_multi'
    post 'questions/destroy_multi' => 'questions#destroy_multi'
    post 'societies/destroy_multi' => 'societies#destroy_multi'
    post 'sources/destroy_multi' => 'sources#destroy_multi'
    post 'sub_colleges/destroy_multi' => 'sub_colleges#destroy_multi'
    resources :roles
    resources :attachments
    resources :code_tables
    resources :organizations
    resources :permissions
    resources :answers
    resources :articles
    resources :article_types
    resources :associations
    resources :fellows
    resources :majors
    resources :notices
    resources :questions
    resources :societies
    resources :sources
    resources :sub_colleges
    resources :users do
      collection do
        get 'validate_user'
        get 'update_password'
        patch 'update_password'
      end
    end
  end

end

app/models/permission.rb
class Permission < ActiveRecord::Base
  belongs_to :group, class_name: 'CodeTable'

  has_many :role_permissions, dependent: :delete_all
  has_many :roles, through: :role_permissions

  validate :validate_action_value

  def validate_action_value
    unless self.action.start_with? ':'
      errors.add(:action, "请用冒号开始，如: ':manage'")
    end
  end

  def use_subject
    if self.subject == 'all'
      self.subject.to_sym
    else
      self.subject.constantize
    end
  end

  def use_action
    eval(self.action)
  end

end

app/controllers/admin/permissions_controller.rb
# coding: UTF-8
class Admin::PermissionsController < Admin::BaseController
  before_action :base_breadcrumb
  before_action :set_permission, only: [:show, :edit, :update, :destroy]
  before_action :name_breadcrumb_handler, only: [:show, :edit]
  before_action :action_common_breadcurmb, only: [:new, :edit]
  # GET /admin/permissions
  def index
    @permissions = initialize_grid(Permission, page: params[:page], order: :created_at, order_direction: :desc)
  end

  # GET /admin/permissions/1
  def show
  end

  # GET /admin/permissions/new
  def new
    @permission = Permission.new
  end

  # GET /admin/permissions/1/edit
  def edit
  end

  # POST /admin/permissions
  def create
    @permission = Permission.new(permission_params)

    respond_to do |format|
      if @permission.save
        format.html { redirect_to admin_permission_path(@permission.id), notice: create_success_notice(:permission) }
       format.json { render action: 'show', status: :created, location: @permission }
      else
        format.html { render action: 'new' }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/permissions/1
  def update
    respond_to do |format|
      if @permission.update_attributes(permission_params)
       format.html { redirect_to admin_permission_path(@permission.id), notice: update_success_notice(:permission) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/permissions/1
  def destroy
    begin
      @permission.destroy
    rescue
      @permission.update_attributes(enable: false)
    end

    respond_to do |format|
      format.html { redirect_to admin_permissions_path, notice: destroy_success_notice(:permission) }
      format.json { head :no_content }
    end
  end

  def destroy_multi
    ids =params[:grid][:select_ids]
    if ids and ids.instance_of? Array
      ids.each do |id|
        permission = Permission.find(id)
        begin
          permission.destroy! if permission
        rescue ActiveRecord::RecordNotDestroyed
          permission.update_attributes(enable: false)
          next
        end
      end
    end
  rescue
    flash[:notice] ="#{t 'common.delete_multi'}#{t 'common.fault'}"
    redirect_to action: 'index'
  else
    flash[:notice] ="#{t 'common.delete_multi'}#{t 'common.success'}"
    redirect_to action: 'index'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_permission
    if params[:action] == 'show'
       @permission = Permission.find(params[:id])
    else
      @permission = Permission.find(params[:id])
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def permission_params
    params.require(:permission).permit(:action, :subject, :description, :code, :group_id, :fetching)
  end

  def base_breadcrumb
    add_breadcrumb (t 'activerecord.attributes.permission.admin_title'), admin_permissions_path
  end

  # add name breadcrumb with :show, :edit
  def name_breadcrumb_handler
    add_breadcrumb @permission.description, admin_permission_path(@permission.id), class: :pjax
  end
end

app/helpers/admin/permissions_helper.rb
module Admin::PermissionsHelper
end

app/views/admin/permissions/_form.html.erb
<%= simple_form_for([:admin, @permission], html: {class: 'form-horizontal form-show', id: 'permission_form'}) do |f| %>
    <%= f.error_notification %>

    <%= f.input :description, required: true %>
    <%= f.input :action, required: true, placeholder: "请用冒号开始，如: ':manage'" %>
    <%= f.input :subject, required: true do %>
        <%= f.select :subject, ActiveRecord::Base.descendants.map(&:name) %>
    <% end %>
    <%= f.input :code, as: :text %>
    <%= f.input :fetching %>
    <%= f.association :group %>

    <div class="clearfix form-actions">
      <div class="col-md-offset-3 col-md-9">
        <%= f.button :submit, class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>

<script>
    $(function () {
        $('#permission_form').validator_b3({
            errorElement: 'div',
            errorClass: 'help-block',
            focusInvalid: false,
            rules: {},
            messages: {}
        });


        $('.nav.nav-list li.active').removeClass('active');
        $('.nav.nav-list li[data-model="permission_list"]').addClass('active');
    });
</script>

app/views/admin/permissions/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= render partial: 'common/nav', locals: {show_tab: :edit, model_nav_name: :admin_permission, pjax: true} %>
    <%= render 'form' %>
  </div>
</div>

app/views/admin/permissions/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= render partial: 'common/nav', locals: {show_tab: :index, model_nav_name: :admin_permission, pjax: true} %>
    <div id="admin_permissions">
      <%= form_for 'Permission', url: admin_permissions_destroy_multi_path, method: :post, data: { confirm: "#{  t 'common.confirm_delete'}"} do %>
          <button class="btn btn-minier btn-danger" type="submit">
            <i class="icon-trash"></i> <%= t 'common.delete_multi' %></button>
          <%= grid(@permissions, show_filters: :when_filtered) do |g|
            g.action_column param_name: :select_ids, object_property: :id
            g.column name: "#{t 'activerecord.attributes.defaults.id'}", attribute: 'id', filter: false, ordering: true
            g.column name: "#{t 'activerecord.attributes.permission.description'}", attribute: 'description' do |c|
              link_to c.description, admin_permission_path(c.id), class: :pjax
            end
            g.column name: "#{t 'activerecord.attributes.permission.action'}", attribute: 'action'
            g.column name: "#{t 'activerecord.attributes.permission.subject'}", attribute: 'subject'
            g.column name: "#{t 'activerecord.attributes.permission.group'}" do |t|
              t.group.name if t.group
            end

            g.column do |c|
              grid_operator(:admin_permission_path, c.id)
            end
          end %>
      <% end %>
    </div>
  </div>
</div>

<script>
    $(function () {
        $('.nav.nav-list li.active').removeClass('active');
        $('.nav.nav-list li[data-model="permission_list"]').addClass('active');
    });
</script>

app/views/admin/permissions/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= render partial: 'common/nav', locals: {show_tab: :new, model_nav_name: :admin_permission, pjax: true} %>
    <%= render 'form' %>
  </div>
</div>

app/views/admin/permissions/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= render partial: 'common/nav', locals: {show_tab: :show, model_nav_name: :admin_permission, pjax: true} %>
    <div class="form-horizontal form-show" id="admin_permission">
          <div class="form-group">
            <label class="control-label col-xs-12 col-sm-3"><%= t 'activerecord.attributes.permission.action' %></label>
            <div class="col-xs-12 col-sm-9">
              <div class="clearfix">
                    <input type="text" readonly="readonly" class="col-xs-12 col-sm-6" value="<%= @permission.action %>">
              </div>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-xs-12 col-sm-3"><%= t 'activerecord.attributes.permission.subject' %></label>
            <div class="col-xs-12 col-sm-9">
              <div class="clearfix">
                    <input type="text" readonly="readonly" class="col-xs-12 col-sm-6" value="<%= @permission.subject %>">
              </div>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-xs-12 col-sm-3"><%= t 'activerecord.attributes.permission.description' %></label>
            <div class="col-xs-12 col-sm-9">
              <div class="clearfix">
                    <input type="text" readonly="readonly" class="col-xs-12 col-sm-6" value="<%= @permission.description %>">
              </div>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-xs-12 col-sm-3"><%= t 'activerecord.attributes.permission.code' %></label>
            <div class="col-xs-12 col-sm-9">
              <div class="clearfix">
                    <input type="text" readonly="readonly" class="col-xs-12 col-sm-6" value="<%= @permission.code %>">
              </div>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-xs-12 col-sm-3"><%= t 'activerecord.attributes.permission.group_id' %></label>
            <div class="col-xs-12 col-sm-9">
              <div class="clearfix">
                    <input type="text" readonly="readonly" class="col-xs-12 col-sm-6" value="<%= @permission.group_id %>">
              </div>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-xs-12 col-sm-3"><%= t 'activerecord.attributes.permission.fetching' %></label>
            <div class="col-xs-12 col-sm-9">
              <div class="clearfix">
                    <input type="text" readonly="readonly" class="col-xs-12 col-sm-6" value="<%= @permission.fetching %>">
              </div>
            </div>
          </div>
    </div>
  </div>
</div>
<script>
    $(function () {
        $('.nav.nav-list li.active').removeClass('active');
        $('.nav.nav-list li[data-model="permission_list"]').addClass('active');
    } );
</script>