config/routes.rb
Scaffold::Application.routes.draw do
  devise_for :users, skip: [:registrations], controllers: {sessions: 'common/sessions'}

  root 'admin/users#index'
  get 'admin' => 'admin/users#index'
  namespace :front do |front|
    namespace :users do
      get :show
      post :sign_up
      post :validate, action: :validate!
      get :current
      post :sign_in_for_web
      post :sign_out_for_web
      get :get_rank
      post :user_approve
      get :search_friend
      get :school_email_approve
      get :get_total_rank
      get :get_total_rank_for_angular
      post :update
      post :update_only_four_info
    end
    resources :contacts do
      collection do
        get :upload
        post :upload_file
        get :tree_data, format: 'json'
      end
    end

    get 'users/edit' => 'users#edit'
    patch 'users/:id' => 'users#update'
    get 'users/update_password' => 'users#update_password'
    patch 'users/update_password' => 'users#update_password'
    resources :user_bills, only: [:index, :show]
    resources :answers do
      collection do
        post 'praise'
        get 'index_for_angular'
        get 'user_already_answer'
        get 'user_already_answer_for_angular'
        get 'answers_praise_num'
        post 'create_with_picture'
      end
    end
    resources :articles
    resources :article_types
    post 'association/judge_praise' => 'association#judge_praise'
    post 'association/fellow_list' => 'association#fellow_list'
    get 'association/fellow_list' => 'association#fellow_list'
    resources :fellows
    resources :majors
    resources :notices
    resources :questions do
      collection do
        get 'index_for_angular'
        post 'search'
        get 'recommend_info'
        get 'user_already_ask'
        get 'add_read_num'
        get 'question_hottest'
        get 'recommend_info_for_angular'
        get 'user_already_ask_for_angular'
        get 'question_hottest_for_angular'
        post 'create_with_picture'
      end
    end
    resources :societies
    resources :sources
    resources :sub_colleges
  end

  namespace :admin do |admin|

    get 'roles/tree_data/:type' => 'roles#tree_data'
    post 'roles/destroy_multi' => 'roles#destroy_multi'
    post 'users/destroy_multi' => 'users#destroy_multi'
    post 'permissions/destroy_multi' => 'permissions#destroy_multi'
    post 'organizations/destroy_multi' => 'organizations#destroy_multi'
    post 'code_tables/destroy_multi' => 'code_tables#destroy_multi'
    post 'attachments/destroy_multi' => 'attachments#destroy_multi'
    post 'answers/destroy_multi' => 'answers#destroy_multi'
    post 'article_types/destroy_multi' => 'article_types#destroy_multi'
    post 'articles/destroy_multi' => 'articles#destroy_multi'
    post 'associations/destroy_multi' => 'associations#destroy_multi'
    post 'fellows/destroy_multi' => 'fellows#destroy_multi'
    post 'majors/destroy_multi' => 'majors#destroy_multi'
    post 'notices/destroy_multi' => 'notices#destroy_multi'
    post 'questions/destroy_multi' => 'questions#destroy_multi'
    post 'societies/destroy_multi' => 'societies#destroy_multi'
    post 'sources/destroy_multi' => 'sources#destroy_multi'
    post 'sub_colleges/destroy_multi' => 'sub_colleges#destroy_multi'
    resources :roles
    resources :attachments
    resources :code_tables
    resources :organizations
    resources :permissions
    resources :answers
    resources :articles
    resources :article_types
    resources :associations
    resources :fellows
    resources :majors
    resources :notices
    resources :questions
    resources :societies
    resources :sources
    resources :sub_colleges
    resources :users do
      collection do
        get 'validate_user'
        get 'update_password'
        patch 'update_password'
      end
    end
  end

end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render partial: 'layouts/head', locals: {title: (t 'web.org') + (t 'web.manage_system')} %>
</head>
<body>
    <%= render partial: 'layouts/nav', locals: {title: (t 'web.org') + (t 'web.manage_system')} %>

    <div class="main-container" id="main-container">
      <div class="main-container-inner">
        <a class="menu-toggler" id="menu-toggler" href="#">
          <span class="menu-text"></span>
        </a>
        <div class="sidebar" id="sidebar">
          <script type="text/javascript">
              try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
          </script>
          <ul class="nav nav-list">

            <% if can? :manage, User %>
                <li data-model="user_list">
                  <%= link_to admin_users_path do %>
                      <i class="icon-user"></i>
                      <span class="menu-text"> <%= t 'activerecord.attributes.user.admin_title' %> </span>
                  <% end %>
                </li>
            <% end %>
            <% if can? :manage, Role %>
                <li data-model="role_list">
                  <%= link_to admin_roles_path do %>
                      <i class="icon-key"></i>
                      <span class="menu-text"> <%= t 'activerecord.attributes.role.admin_title' %> </span>
                  <% end %>
                </li>
            <% end %>

            <% if can? :manage, Permission %>
                <li data-model="permission_list">
                  <%= link_to admin_permissions_path do %>
                      <i class="icon-lock"></i>
                      <span class="menu-text"> <%= t 'activerecord.attributes.permission.admin_title' %> </span>
                  <% end %>
                </li>
            <% end %>
            <% if can? :manage, Answer %>
                <li data-model="answer_list">
                  <%= link_to admin_answers_path do %>
                      <i class="icon-envelope"></i>
                      <span class="menu-text"> <%= t 'activerecord.attributes.answer.admin_title' %> </span>
                  <% end %>
                </li>
            <% end %>
            <% if can? :manage, Article %>
                <li data-model="article_list">
                  <%= link_to admin_articles_path do %>
                      <i class="icon-folder-close"></i>
                      <span class="menu-text"> <%= t 'activerecord.attributes.article.admin_title' %> </span>
                  <% end %>
                </li>
            <% end %>
            <% if can? :manage, ArticleType %>
                <li data-model="article_type_list">
                  <%= link_to admin_article_types_path do %>
                      <i class="icon-folder-open"></i>
                      <span class="menu-text"> <%= t 'activerecord.attributes.article_type.admin_title' %> </span>
                  <% end %>
                </li>
            <% end %>
            <% if can? :manage, Association %>
                <li data-model="Association_list">
                  <%= link_to admin_associations_path do %>
                      <i class="icon-cog"></i>
                      <span class="menu-text"> <%= t 'activerecord.attributes.association.admin_title' %> </span>
                  <% end %>
                </li>
            <% end %>
            <% if can? :manage, Fellow %>
                <li data-model="fellow_list">
                  <%= link_to admin_fellows_path do %>
                      <i class="icon-sitemap"></i>
                      <span class="menu-text"> <%= t 'activerecord.attributes.fellow.admin_title' %> </span>
                  <% end %>
                </li>
            <% end %>
            <% if can? :manage, Major %>
                <li data-model="major_list">
                  <%= link_to admin_majors_path do %>
                      <i class="icon-comments"></i>
                      <span class="menu-text"> <%= t 'activerecord.attributes.major.admin_title' %> </span>
                  <% end %>
                </li>
            <% end %>
            <% if can? :manage, Notice %>
                <li data-model="notice_list">
                  <%= link_to admin_notices_path do %>
                      <i class="icon-volume-down"></i>
                      <span class="menu-text"> <%= t 'activerecord.attributes.notice.admin_title' %> </span>
                  <% end %>
                </li>
            <% end %>
            <% if can? :manage, Question %>
                <li data-model="question_list">
                  <%= link_to admin_questions_path do %>
                      <i class="icon-question"></i>
                      <span class="menu-text"> <%= t 'activerecord.attributes.question.admin_title' %> </span>
                  <% end %>
                </li>
            <% end %>
            <% if can? :manage, Society %>
                <li data-model="society_list">
                  <%= link_to admin_societies_path do %>
                      <i class="icon-smile"></i>
                      <span class="menu-text"> <%= t 'activerecord.attributes.society.admin_title' %> </span>
                  <% end %>
                </li>
            <% end %>
            <% if can? :manage, SubCollege %>
                <li data-model="sub_college_list">
                  <%= link_to admin_sub_colleges_path do %>
                      <i class="icon-fire"></i>
                      <span class="menu-text"> <%= t 'activerecord.attributes.sub_college.admin_title' %> </span>
                  <% end %>
                </li>
            <% end %>
            <!--
            <% if can? :manage, Organization %>
                <li data-model="organization_list">
                  <%= link_to admin_organizations_path do %>
                      <i class="icon-group"></i>
                      <span class="menu-text"> <%= t 'activerecord.attributes.organization.admin_title' %> </span>
                  <% end %>
                </li>
            <% end %>
            <% if can? :manage, CodeTable %>
                <li data-model="code_table_list">
                  <%= link_to admin_code_tables_path do %>
                      <i class="icon-book"></i>
                      <span class="menu-text"> <%= t 'activerecord.attributes.code_table.admin_title' %> </span>
                  <% end %>
                </li>
            <% end %>
            ge'm-->
            <% if can? :manage, Permission %>
                <li data-model="attachment_list">
                  <%= link_to admin_attachments_path do %>
                      <i class="icon-cloud-upload"></i>
                      <span class="menu-text"> <%= t 'activerecord.attributes.attachment.admin_title' %> </span>
                  <% end %>
                </li>
            <% end %>


          </ul>
          <div class="sidebar-collapse" id="sidebar-collapse">
            <i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
          </div>

          <script type="text/javascript">
              try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
          </script>
        </div>
        <div class="main-content" data-pjax-container>
          <%= render template: 'layouts/admin/pjax' %>
        </div>
        <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
          <i class="icon-double-angle-up icon-only bigger-110"></i>
        </a>
      </div><!-- /.main-container-inner -->
    </div>
    <script>
        $(function() {
            $(document).pjax('a.pjax:not([data-remote]):not([data-behavior]):not([data-skip-pjax])', '[data-pjax-container]');
        });
    </script>
</body>
</html>

app/views/layouts/admin/pjax.html.erb
<%= render partial: 'layouts/breadcrumbs' %>
<%= bootstrap_flash %>
<div class="page-content">
  <%= yield %>
</div><!-- /.page-content -->
<footer class="center">
  <p>&copy; 2015</p>
</footer>